language: python

services:
  - docker

before_install:
  - docker build --file=./docker/Dockerfile --tag=tnet-server-tests .

script:
  - docker run -v $$(pwd)/test:/build/test/ -v $$(pwd)/scripts:/build/scripts/ \
    -ti tnet-server-tests /build/scripts/tests.sh
  - docker run -v $$(pwd)/tnetserver:/build/tnetserver/ \
    -v $$(pwd)/setup.py:/build/setup.py \
    -v $$(pwd)/scripts:/build/scripts/ \
    -ti tnet-test /build/scripts/package.sh
